stages:
  - test

test_job:
  stage: test
  tags:
    - common
  before_script:
    - add-apt-repository ppa:deadsnakes/ppa -y
    - apt-get install python3.11 -y
    - pip3 install -r requirements.txt
  script:
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml
    when: always