stages:
  - test

test_job:
  stage: test
  tags:
    - dind
  before_script:
    - apt-get update -y
    - apt-get install software-properties-common -y
    - add-apt-repository ppa:deadsnakes/ppa -y
    - apt-get update -y
    - apt-get install python3.11 -y
    - python3.11 -m pip install -r requirements.txt
  script:
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml
    when: always