stages:
  - test

test_job:
  stage: test
  tags:
    - common
  before_script:
    - apt-get update -y
    - apt-get install -y python3-pip
    - pip3 install -r requirements.txt
  script:
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: report.xml
    when: always