@startuml use_case_uml

skinparam actorStyle awesome
left to right direction

package ClientFacade {
    (create_account) as create_account_facade
    (deposit)
    (withdraw)
    (transfer)
}

actor User
User -- create_account_facade
User -- deposit
User -- withdraw
User -- transfer


package Transaction {
    (perform)
    (cancel)
}
deposit -- perform
withdraw -- perform
transfer -- perform

package ClientObject {
    (Edit Fileds) as Edit
    (create_account)
}
create_account_facade -- create_account

actor "Bank Admin" as Admin

(Create Client Step by Step) as CreateClient
Admin -- CreateClient
CreateClient -- Edit

(Cancel Transaction) as Cancel

Admin -- Cancel
Cancel -- cancel
' cancel -> perform

' package "Account Transaction History" {
'     (save)
' }
' perform -- save


@enduml